spring:
  kafka:
    bootstrap-servers: localhost:9092
#    bootstrap-servers:
#      localhost:
#        server:
#          port: 9092
#spring:
#    kafka:
#      producer:
#        value-serializer: org.example.metrics.service.CustomJsonSerializer
#        properties:
#          spring.json.add.type.headers: false
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 9090